import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";
import Providers from "@/components/Provides/Provides";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-canvasDark text-white`}>
                <main>
                    <Header />
                    <div className="flex w-full flex-col gap-y-6 px-9  p-6 h-[calc(100vh)]">
                        <div className="h-full  justify-start">
                            <Providers>  {children}  </Providers>
                        </div>
                    </div>
                    </main>
            </body>
        </html>
    );
}
